-- 코드를 입력하세요
SELECT F.FLAVOR FROM FIRST_HALF F JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS J_TOTAL FROM JULY
    GROUP BY FLAVOR
) AS J 
ON F.FLAVOR = J.FLAVOR
GROUP BY FLAVOR
ORDER BY F.TOTAL_ORDER + J.J_TOTAL DESC
LIMIT 3;

-- 코드를 입력하세요
SELECT F.FLAVOR FROM FIRST_HALF F LEFT JOIN (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR 
) J ON F.SHIPMENT_ID = J.SHIPMENT_ID ORDER BY (F.TOTAL_ORDER + J.TOTAL_ORDER) DESC LIMIT 3;