-- 코드를 작성해주세요
SELECT
    ID, FISH_NAME, LENGTH
FROM(
    SELECT
        I.ID AS ID, N.FISH_NAME AS FISH_NAME, I.LENGTH AS LENGTH,
        ROW_NUMBER() OVER (PARTITION BY I.FISH_TYPE ORDER BY LENGTH DESC) AS RNK
    FROM
        FISH_INFO I
    JOIN
        FISH_NAME_INFO N
    ON
        I.FISH_TYPE = N.FISH_TYPE
) AS SORT
WHERE
    RNK = 1
ORDER BY
    ID ASC;
